apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /network-function1
  name: network-function
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|network-function1'
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-function
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-function
    spec:
      containers:
      - name: nginx
        image: nginx:latest
